name: reactworkflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: "git clone https://github.com/balajirajmohan/githubactions.git" 
            - name: change folder
              run: " cd githubactions"
            - name: run npm install
              run: "npm install"
            - name: run npm test
              run: "npm test"
              
            
    
