name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all the files
        run: " ls -lrth"
      - name: print greeting
        run: echo "Hello world"
      - name: print you are good to go
        run: echo "Welcome, you are good to go"
