name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone the github repo
        run: " git clone https://github.com/jaygajera17/E-commerce-project-springBoot.git "
      - name: switch to github repo folder
        run: " cd E-commerce-project-springBoot/"
      - name: List all the files
        run: " ls -lrth"
      - name: print greeting
        run: echo "Hello world"
      - name: print you are good to go
        run: echo "Welcome, you are good to go"

        
